digitalstrategie/settings/base.py, digitalstrategie/templates/base.html, package.json, requirements/base.txt, webpack.common.js, webpack.dev.js, webpack.prod.js
* Upgrade to Django 3.2 as the new LTS release
* Fix an error in the webpack.prod config
* Update webpack
* Remove unusued and unmaintained packages
=> Jd 2021 09 django 3 webpack

apps/contrib/elasticsearch.py, apps/contrib/views.py, apps/home/models.py, digitalstrategie/settings/base.py, digitalstrategie/templates/search_results.html
* subclass the elasticsearch wagtail class
* extract and append the highlights to the queryset
* display highlights in search result page
=> search: improve search results

digitalstrategie/assets/scss/components/_richtext.scss
=> richtext/images: using css to format image

digitalstrategie/assets/scss/components/_ds-block.scss
=> blocks/teaser-image/green: fix green overlay

apps/home/templates/apps_home/blocks/teaser_block_tiles.html, digitalstrategie/assets/scss/components/_ds-block.scss
closes #364 
closes #365 
closes #368
=> blocks/issues: spacing headings and green button background issue

apps/forms/models.py, digitalstrategie/urls.py
Ups! Don't know how it was working before... I hope this fixes https://sentry.liqd.net/organizations/liqd/issues/1837/
=> Kl 2022 03 robots

package.json, webpack.common.js
=> deps: remove fontawesome dep

.editorconfig, .isort.cfg
move out of .editorconfig as it clashes with some editors
=> move isort config to file

apps/settings/models.py, digitalstrategie/settings/base.py, renovate.json, requirements/base.txt
branch off wagtail3 branch, that should be merged first
=> [#6627] deps wagtail4

apps/home/templates/apps_home/blocks/faq_block.html, apps/home/templates/apps_home/blocks/newsletter_block.html, apps/home/templates/apps_home/blocks/paragraph_block.html, apps/home/templates/apps_home/blocks/quote_block.html, apps/home/templates/apps_home/blocks/teaser_block_centered.html, apps/home/templates/apps_home/blocks/teaser_block_columns.html, apps/home/templates/apps_home/blocks/teaser_block_image.html, apps/home/templates/apps_home/blocks/teaser_block_single.html, apps/home/templates/apps_home/blocks/teaser_block_tiles.html, apps/home/templates/apps_home/blocks/text_with_image_block.html, apps/home/templates/apps_home/blocks/thesis_block.html, apps/home/templates/apps_home/blocks/thesis_list_block.html, digitalstrategie/assets/scss/_base.scss, digitalstrategie/assets/scss/components/_ds-block-overwrites.scss, digitalstrategie/assets/scss/components/_ds-block.scss, digitalstrategie/assets/scss/components/_thesis-ds-block.scss, digitalstrategie/templates/base.html
=> [#6514] styleguide fixes after library download

locale/de/LC_MESSAGES/django.po
That was the only issue I could fix and that didn't need a decision.
=> translations: fix wording contact form - fixes #473

apps/forms/models.py, apps/home/templates/apps_home/blocks/teaser_block_image.html, apps/home/templates/apps_home/blocks/text_with_image_block.html, apps/home/templates/apps_home/blocks/thesis_list_block.html, digitalstrategie/assets/scss/components/_ds-block-overwrites.scss, digitalstrategie/assets/scss/components/_ds-block.scss, locale/de/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/django.po
also may fix #533 but cannot currently check
=> Pm 2022 11 mobile img

Makefile, apps/captcha/__init__.py, apps/captcha/apps.py, apps/captcha/assets/captcheck.js, apps/captcha/fields.py, apps/captcha/templates/captcheck_captcha_widget.html, apps/captcha/widgets.py, apps/contrib/templatetags/form_field_tags.py, apps/forms/models.py, apps/forms/templates/apps_forms/includes/form.html, apps/forms/templates/apps_forms/includes/form_field.html, apps/settings/helpers.py, digitalstrategie/settings/base.py, digitalstrategie/settings/dev.py, digitalstrategie/templates/base.html, digitalstrategie/urls.py, locale/de/LC_MESSAGES/django.po, locale/de/LC_MESSAGES/djangojs.po, locale/de_ls/LC_MESSAGES/django.po, locale/de_ls/LC_MESSAGES/djangojs.po, locale/en/LC_MESSAGES/django.po, locale/en/LC_MESSAGES/djangojs.po, webpack.common.js
=> [#6604] add captcha to forms

digitalstrategie/settings/base.py, digitalstrategie/settings/dev.py, requirements/base.txt
Reverts liqd/digitalstrategie#666
=> Revert "add initial content-security-policy"

apps/home/templatetags/custom_metadata_tags.py
=> metadata: fix error if request is None

apps/home/templates/apps_home/blocks/video_block.html, apps/settings/wagtail_hooks.py
=> [issues] styling issue fixes

apps/contrib/templatetags/contrib_tags.py, apps/measures/models.py, apps/measures/templates/apps_measures/includes/measures_filter.html, apps/measures/templates/apps_measures/measures_overview_page.html, digitalstrategie/assets/scss/components/_button.scss
The cross to remove the search is still missing, will add it as a task
Right, and you need elasricsearch running for that.
Try:
`sudo docker run --name es01-test -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" -e "logger.level=DEBUG" docker.elastic.co/elasticsearch/elasticsearch:7.17.10`
if that tells you, that the container is already in use, delete it: 
`docker rm -f es01-test`
And again the thing from above. When elasticsearch is running, in another window:
`python manage.py update_index`
And now with that you are ready to also `make watch` and try the search!
=> apps/measures/overview: add search

apps/measures/models.py, apps/measures/templates/apps_measures/includes/measures_filter.html, apps/measures/templates/apps_measures/measures_overview_page.html, digitalstrategie/templates/includes/pagination.html, digitalstrategie/templates/search_results.html
Not sure, I succeeded with the second commit and made it really more readable. Well, I tried.
=> [7362] add sentences to show search, filters and result count and some measure overview related fixes

apps/measures/models.py, apps/measures/templates/apps_measures/measures_overview_page.html
The `pill` was the closest, I could find in the verticals. Hope it's fine!
=> apps/measures: add filter count - fixes #700

digitalstrategie/settings/base.py
see styleguide wiki for more info on the parameters
fixes broken footer on small screens
=> footer: add parameter to exclude js from the include file

digitalstrategie/settings/dev.py
=> settings:dev: add data: to IMG_SRC csp t oallow base64 svgs from BO

apps/contrib/translations.py, changelog/_0001.md, tests/contrib/test_translations.py
=> apps/contrib: create correct list of simple german fields for the search
